config/routes.rb
Rails.application.routes.draw do
  
  

  
  

  get 'new' =>'partidos#new'

  get 'partidos/create'

  get 'partidos/show'

  get 'static_pages/home'
  
  get 'futbols/opcion'
  
  get 'reviews/parse_comments'
  
resources :futbols do
  resources :reviews
end

resources :games do
  resources :bets
end

  

   root 'static_pages#home'

end

app/models/futbol.rb
class Futbol < ActiveRecord::Base
      has_many :reviews
        default_scope -> { order(created_at: :desc) }

end

app/controllers/futbols_controller.rb
class FutbolsController < ApplicationController
  helper_method :suma_resultados
  
  def index
    @futbol = Futbol.paginate(:page => params[:page], :per_page => 7)
  end
  
  
  def new
    @futbol = Futbol.new
  end

  def create
    
    @futbol = Futbol.new(futbol_params)
 
    if @futbol.save
      redirect_to root_path
      else
      render 'new'
    end
    end

  def show
    @futbol = Futbol.find(params[:id])
  
      respond_to do |format|
      format.html 
      format.js
      format.json { render json: @futbol }
    end

  end
  
  def edit
    @futbol = Futbol.find(params[:id])
  end
  
  def update
    @futbol = Futbol.find(params[:id])
 
    if @futbol.update(futbol_params)
      redirect_to @futbol
    else
      render 'edit'
    end
  end
  
  def destroy
    @futbol = Futbol.find(params[:id])
    @futbol.destroy
 
    redirect_to root_path
  end
  
  def suma_resultados
    total_count = 0
    @futbol = Futbol.find(params[:id])
    total_count = @futbol.unoxdosuno + @futbol.unoxdosequix
    total_count
  end
  
  private
  def futbol_params
    params.require(:futbol).permit(:local, :visitante, :unoxdosuno, :unoxdosequix, :unoxdosdos, :column_fecha)
  end
end

app/helpers/futbols_helper.rb
module FutbolsHelper
end

app/views/futbols/_form.html.erb
<div class="container">
    <div class='row'>
     <%= form_for (@futbol) do |f| %>
        <div class='col-md-4'></div>
        <div class='col-md-4'>
          <script src='https://js.stripe.com/v2/' type='text/javascript'></script>
            <div class='form-row'>
              <div class='col-xs-12 form-group required'>
                <label class='control-label'>Equipo local</label>
                <!--<input class='form-control' size='4' type='text'>-->
                <%= f.text_field :local,  :class => 'form-control card-expiry-month' %>
              </div>
            </div>
            <div class='form-row'>
              <div class='col-xs-12 form-group card required'>
                <label class='control-label'>Equipo visitante</label>
                <!--<input autocomplete='off' class='form-control card-number' size='20' type='text'>-->
                <%= f.text_field :visitante, :class => 'form-control card-expiry-month' %>
              </div>
            </div>
            <div class='form-row'>
              <div class='col-xs-4 form-group cvc required'>
                <label class='control-label'>Cotización 1</label>
                <%= f.text_field :unoxdosuno, :class => 'form-control card-cvc'%>
              </div>
              <div class='col-xs-4 form-group expiration required'>
                <label class='control-label'>Empate</label>
                <%= f.text_field :unoxdosequix, :class => 'form-control card-cvc'%>
              </div>
              <div class='col-xs-4 form-group expiration required'>
                <label class='control-label'>Cotizacion 2 </label>
                <%= f.text_field :unoxdosdos, :class => 'form-control card-cvc'%>
              </div>
              <div class='col-xs-4 form-group expiration required'>
                <label class='control-label'>Fecha </label>
                <%= f.text_field :column_fecha, :class => 'form-control card-cvc'%>
              </div>
            </div>
            <div class='form-row'>
              <div class='col-md-12 form-group'>
                <%= f.submit "crear partido", :class => 'form-control btn btn-primary submit-button'  %>
              </div>
            </div>
            <div class='form-row'>
              <div class='col-md-12 error form-group hide'>
                <div class='alert-danger alert'>
                  Please correct the errors and try again.
                </div>
              </div>
            </div>
          </form>
        </div>
        <div class='col-md-4'></div>
        <% end %>
    </div>
</div>

app/views/futbols/create.html.erb
<h1>Futbols#create</h1>
<p>Find me in app/views/futbols/create.html.erb</p>

app/views/futbols/edit.html.erb
<h1>Edita el partido</h1>

<%= render 'form' %>

<%= link_to 'Back', futbols_path %>

app/views/futbols/index.html.erb
<h1>Lista de partidos por vencedor</h1>

<div class="container">
  <% @futbol.each do |f| %>
    <tr>
            <div class="col-sm-12">

<div class="bs-calltoaction bs-calltoaction-danger">
                    <div class="row">
                        <div class="col-md-9 cta-contents">
                            <h1 class="cta-title"><%= f.local %> vs <%= f.visitante %></h1>
                            <div class="cta-desc">
                                
                            </div>
                        </div>
                        <div class="col-md-3 cta-button">
                          <a><%= link_to 'entrar', futbol_path(f), :class => "btn btn-lg btn-block btn-danger" %></a>
                        </div>
                     </div>
                </div>
            </div>
              </tr>
  <% end %>
        </div>
        <%= will_paginate @futbol %>

app/views/futbols/new.html.erb
<h1>Crear un nuevo partido por ganador</h1>

<%= render 'form' %>

app/views/futbols/opcion.html.erb
<h1>Elige una opcion</h1>
<p>
  <strong>Title:</strong>
  <%= @futbol.local %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @futbol.visitante %>
</p>

app/views/futbols/show.html.erb
<h1><%= @futbol.local %> vs <%= @futbol.visitante %></h1>
<!--<p>Find me in app/views/futbols/show.html.erb</p>-->

<!--<p>-->
<!--  <strong>Equipo local</strong>-->
<!--  <%= @futbol.local %>-->
<!--</p>-->
 
<!--<p>-->
<!--  <strong>Visitante</strong>-->
<!--  <%= @futbol.visitante %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>1x2 relutado de 1</strong>-->
<!--  <%= @futbol.unoxdosuno %>-->
<!--</p>-->
<!--<%= @variable %>-->

<!--<p>-->
<!--  <strong>1x2 relutado de empate</strong>-->
<!--  <%= @futbol.unoxdosequix %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>1x2 relutado de 2</strong>-->
<!--  <%= @futbol.unoxdosdos %>-->
<!--</p>-->

<!--<tr id="sum">-->
<!--        <td>&nbsp;</td>-->
<!--        <td align="right">Sum :</td>-->
<!--        <td align="center"><span id="sumada">0</span></td>-->
<!--    </tr>-->
<!--  </p>-->

  <!--<input type="text" id="txt_name"  />-->
  
  <div class="row">
  <div class="col-lg-3">
    <div class="input-group">
      <span class="input-group-btn">
        <button class="btn btn-default btn-lg" id="capullo"> Testea</button>
      </span>
      <input type="text" class="form-control" id="amount" >
    </div>
  </div>
</div>
<div class="container features_table">
        	<div class="col-sm-8 col-8 col-xs-12 no-padding">
            	<div class="features-table">
                	<ul>
                    	<h1>Apuestas</h1>
                    	<li>1x2 con resultado 1</li>
                        <li>1x2 con resultado x</li>
                        <li>1x2 con resultado 2</li>
                        
                    </ul>
                </div>
            </div>
            <div class="col-sm-2 col-2 col-xs-12 no-padding">
            <div class="features-table-free">
                	<ul>
                    	<h1>Contización</h1>
                        <li><i class="fa fa-check"><%= @futbol.unoxdosuno %></i></li>
                        <li><i class="fa fa-check"><%= @futbol.unoxdosequix %></i></li>
                        <li><i class="fa fa-check"><%= @futbol.unoxdosdos %></i></li>
                        
                    </ul>
                </div>
            
            </div>
             <div class="col-sm-2 col-2 col-xs-12 no-padding">
             	 <div class="features-table-paid">
                	<ul>
                    	<h1>Ganancias</h1>
                        <li><i class="fa fa-check" id="sumada">0</i></li>
                        <li><i class="fa fa-check" id="sumada1">0</i></li>
                        <li><i class="fa fa-check" id="sumada2">0</i></li>
                        
                    </ul>
                </div>
             </div>
        </div>
  


<%= link_to 'Editar', edit_futbol_path(@futbol) %>

<%= link_to "Procesar apuesta", new_futbol_review_path(@futbol), :class => "btn btn-default btn-lg" %>

app/views/futbols/show.js.erb
$('#prueba-link').hide();