config/routes.rb
Rails.application.routes.draw do
  
  

  
  

  get 'new' =>'partidos#new'

  get 'partidos/create'

  get 'partidos/show'

  get 'static_pages/home'
  
  get 'futbols/opcion'
  
  get 'reviews/parse_comments'
  
resources :futbols do
  resources :reviews
end

resources :games do
  resources :bets
end

  

   root 'static_pages#home'

end

app/models/game.rb
class Game < ActiveRecord::Base
    has_many :bets
    default_scope -> { order(created_at: :desc) }
    validates :local, :visitante, :unoxcero, :dosxcero, :dosxuno, :tresxcero, :tresxuno, :tresxdos, :cuatroxcero, :cuatroxuno, :cuatroxdos, :cuatroxtres, :cincoxcero, :ceroxcero, :unoxuno, :dosxdos, :tresxtres, :cuatroxcuatro, :ceroxuno, :ceroxdos, :unoxdos, :ceroxtres, :unoxtres, :dosxtres, :ceroxcuatro, :unoxcuatro, :dosxcuatro, :tresxcuatro, :presence => {:message => 'Name cannot be blank, Task not saved'}
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    
  def index
      @game = Game.paginate(:page => params[:page], :per_page => 7)
  end
      
  def new
    @game = Game.new
  end

  def create
    
    @game = Game.new(game_params)
 
    if @game.save
      redirect_to games_path
      else
      render 'new'
    end
    end

  def show
    @game = Game.find(params[:id])
  
      respond_to do |format|
      format.html 
      format.js
      format.json { render json: @game }
    end

  end
  
  def edit
    @game = Game.find(params[:id])
  end
  
  def update
    @game = Game.find(params[:id])
 
    if @game.update(game_params)
      redirect_to @game
    else
      render 'edit'
    end
  end
  
  def destroy
    @game = Game.find(params[:id])
    @game.destroy
 
    redirect_to root_path
  end
  
#   def suma_resultados
#     total_count = 0
#     @futbol = Futbol.find(params[:id])
#     total_count = @futbol.unoxdosuno + @futbol.unoxdosequix
#     total_count
#   end
  
  private
  def game_params
    params.require(:game).permit(:local, :visitante, :unoxcero, :dosxcero, :dosxuno, :tresxcero, :tresxuno, :tresxdos, :cuatroxcero, :cuatroxuno, :cuatroxdos, :cuatroxtres, :cincoxcero, :ceroxcero, :unoxuno, :dosxdos, :tresxtres, :cuatroxcuatro, :ceroxuno, :ceroxdos, :unoxdos, :ceroxtres, :unoxtres, :dosxtres, :ceroxcuatro, :unoxcuatro, :dosxcuatro, :tresxcuatro, :otro, :cantidad, :fecha )
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<div class="container">
    <div class='row'>
     <%= form_for (@game) do |f| %>
        <div class='col-md-4'></div>
        <div class='col-md-4'>
          <script src='https://js.stripe.com/v2/' type='text/javascript'></script>
            <div class='form-row'>
              <div class='col-xs-12 form-group required'>
                <label class='control-label'>Equipo local</label>
                <!--<input class='form-control' size='4' type='text'>-->
                <%= f.text_field :local,  :class => 'form-control card-expiry-month' %>
              </div>
            </div>
            <div class='form-row'>
              <div class='col-xs-12 form-group card required'>
                <label class='control-label'>Equipo visitante</label>
                <!--<input autocomplete='off' class='form-control card-number' size='20' type='text'>-->
                <%= f.text_field :visitante, :class => 'form-control card-expiry-month' %>
              </div>
            </div>
            <div class='form-row'>
              <div class='col-xs-3 form-group cvc required'>
                <label class='control-label'> 1-0</label>
                <%= f.text_field :unoxcero, :class => 'form-control card-cvc'%>
              </div>
              <div class='col-xs-3 form-group expiration required'>
                <label class='control-label'>2-0</label>
                <%= f.text_field :dosxcero, :class => 'form-control card-cvc'%>
              </div>
              <div class='col-xs-3 form-group expiration required'>
                <label class='control-label'> 2-1 </label>
                <%= f.text_field :dosxuno, :class => 'form-control card-cvc'%>
              </div>
              <div class='col-xs-3 form-group expiration required'>
                <label class='control-label'> 3-0 </label>
                <%= f.text_field :tresxcero, :class => 'form-control card-cvc'%>
              </div>
            </div>
            <div class='form-row'>
              <div class='col-xs-3 form-group cvc required'>
                <label class='control-label'> 3-1</label>
                <%= f.text_field :tresxuno, :class => 'form-control card-cvc'%>
              </div>
              <div class='col-xs-3 form-group expiration required'>
                <label class='control-label'>3-2</label>
                <%= f.text_field :tresxdos, :class => 'form-control card-cvc'%>
              </div>
              <div class='col-xs-3 form-group expiration required'>
                <label class='control-label'> 4-0 </label>
                <%= f.text_field :cuatroxcero, :class => 'form-control card-cvc'%>
              </div>
              <div class='col-xs-3 form-group expiration required'>
                <label class='control-label'> 4-1 </label>
                <%= f.text_field :cuatroxuno, :class => 'form-control card-cvc'%>
              </div>
            </div>
            <div class='form-row'>
              <div class='col-xs-3 form-group cvc required'>
                <label class='control-label'> 4-2</label>
                <%= f.text_field :cuatroxdos, :class => 'form-control card-cvc'%>
              </div>
              <div class='col-xs-3 form-group expiration required'>
                <label class='control-label'>4-3</label>
                <%= f.text_field :cuatroxtres, :class => 'form-control card-cvc'%>
              </div>
              <div class='col-xs-3 form-group expiration required'>
                <label class='control-label'> 5-0 </label>
                <%= f.text_field :cincoxcero, :class => 'form-control card-cvc'%>
              </div>
              <div class='col-xs-3 form-group expiration required'>
                <label class='control-label'> 0-0 </label>
                <%= f.text_field :ceroxcero, :class => 'form-control card-cvc'%>
              </div>
            </div>
            <div class='form-row'>
              <div class='col-xs-3 form-group cvc required'>
                <label class='control-label'> 1-1</label>
                <%= f.text_field :unoxuno, :class => 'form-control card-cvc'%>
              </div>
              <div class='col-xs-3 form-group expiration required'>
                <label class='control-label'>2-2</label>
                <%= f.text_field :dosxdos, :class => 'form-control card-cvc'%>
              </div>
              <div class='col-xs-3 form-group expiration required'>
                <label class='control-label'> 3-3 </label>
                <%= f.text_field :tresxtres, :class => 'form-control card-cvc'%>
              </div>
              <div class='col-xs-3 form-group expiration required'>
                <label class='control-label'> 4-4 </label>
                <%= f.text_field :cuatroxcuatro, :class => 'form-control card-cvc'%>
              </div>
            </div>
            <div class='form-row'>
              <div class='col-xs-3 form-group cvc required'>
                <label class='control-label'> 0-1</label>
                <%= f.text_field :ceroxuno, :class => 'form-control card-cvc'%>
              </div>
              <div class='col-xs-3 form-group expiration required'>
                <label class='control-label'>0-2</label>
                <%= f.text_field :ceroxdos, :class => 'form-control card-cvc'%>
              </div>
              <div class='col-xs-3 form-group expiration required'>
                <label class='control-label'> 1-2 </label>
                <%= f.text_field :unoxdos, :class => 'form-control card-cvc'%>
              </div>
              <div class='col-xs-3 form-group expiration required'>
                <label class='control-label'> 0-3 </label>
                <%= f.text_field :ceroxtres, :class => 'form-control card-cvc'%>
              </div>
            </div>
            <div class='form-row'>
              <div class='col-xs-3 form-group cvc required'>
                <label class='control-label'> 1-3</label>
                <%= f.text_field :unoxtres, :class => 'form-control card-cvc'%>
              </div>
              <div class='col-xs-3 form-group expiration required'>
                <label class='control-label'>2-3</label>
                <%= f.text_field :dosxtres, :class => 'form-control card-cvc'%>
              </div>
              <div class='col-xs-3 form-group expiration required'>
                <label class='control-label'> 0-4 </label>
                <%= f.text_field :ceroxcuatro, :class => 'form-control card-cvc'%>
              </div>
              <div class='col-xs-3 form-group expiration required'>
                <label class='control-label'> 1-4 </label>
                <%= f.text_field :unoxcuatro, :class => 'form-control card-cvc'%>
              </div>
            </div>
            <div class='form-row'>
              <div class='col-xs-3 form-group cvc required'>
                <label class='control-label'> 2-4</label>
                <%= f.text_field :dosxcuatro, :class => 'form-control card-cvc'%>
              </div>
              <div class='col-xs-3 form-group expiration required'>
                <label class='control-label'>3-4</label>
                <%= f.text_field :tresxcuatro, :class => 'form-control card-cvc'%>
              </div>
              <div class='col-xs-3 form-group expiration required'>
                <label class='control-label'> otro </label>
                <%= f.text_field :otro, :class => 'form-control card-cvc'%>
              </div>
              <div class='col-xs-3 form-group expiration required'>
                <label class='control-label'> Fecha </label>
                <%= f.text_field :fecha, :class => 'form-control card-cvc'%>
              </div>
            <div class='form-row'>
              <div class='col-md-12 form-group'>
                <%= f.submit "crear partido", :class => 'form-control btn btn-primary submit-button'  %>
              </div>
            </div>
            <div class='form-row'>
              <div class='col-md-12 error form-group hide'>
                <div class='alert-danger alert'>
                  Please correct the errors and try again.
                </div>
              </div>
            </div>
          </form>
        </div>
        <div class='col-md-4'></div>
        <% end %>
    </div>
</div>

app/views/games/edit.html.erb
<h1>Edita el partido</h1>

<%= render 'form' %>

<%= link_to 'Back', futbols_path %>

app/views/games/index.html.erb
<h1>Lista de partidos por resultados</h1>

<div class="container">
  <% @game.each do |f| %>
    <tr>
            <div class="col-sm-12">

<div class="bs-calltoaction bs-calltoaction-primary">
                    <div class="row">
                        <div class="col-md-9 cta-contents">
                            <h1 class="cta-title"><%= f.local %> vs <%= f.visitante %></h1>
                            <div class="cta-desc">
                                
                            </div>
                        </div>
                        <div class="col-md-3 cta-button">
                          <a><%= link_to 'entrar', game_path(f), :class => "btn btn-lg btn-block btn-primary" %></a>
                        </div>
                     </div>
                </div>
            </div>
              </tr>
  <% end %>
        </div>
        <%= will_paginate @game %>
        
        

app/views/games/new.html.erb
<h1>Crear un nuevo partido por resultado</h1>

<%= render 'form' %>

app/views/games/show.html.erb
 <div class="row">
  <div class="col-lg-3">
    <div class="input-group">
      <span class="input-group-btn">
        <button class="btn btn-default btn-lg" id="capullo1"> Testea</button>
      </span>
      <input type="text" class="form-control" id="amount1" >
    </div>
  </div>
</div>
<div class="container features_table">
        	<div class="col-sm-8 col-8 col-xs-12 no-padding">
            	<div class="features-table">
                	<ul>
                    	<h1>Apuestas</h1>
                    	<li>1 - 0</li>
                        <li>2 - 0</li>
                        <li>2 - 1</li>
                        <li>3 - 0</li>
                        <li>3 - 1</li>
                        <li>3 - 2</li>
                        <li>4 - 0</li>
                        <li>4 - 1</li>
                        <li>4 - 2</li>
                        <li>4 - 3</li>
                        <li>5 - 0</li>
                        <li>0 - 0</li>
                        <li>1 - 1</li>
                        <li>2 - 2</li>
                        <li>3 - 3</li>
                        <li>4 - 4</li>
                        <li>0 - 1</li>
                        <li>0 - 2</li>
                        <li>1 - 2</li>
                        <li>0 - 3</li>
                        <li>1 - 3</li>
                        <li>2 - 3</li>
                        <li>0 - 4</li>
                        <li>1 - 4</li>
                        <li>2 - 4</li>
                        <li>3 - 4</li>
                        
                        
                        
                    </ul>
                </div>
            </div>
            <div class="col-sm-2 col-2 col-xs-12 no-padding">
            <div class="features-table-free">
                	<ul>
                    	<h1>Contización</h1>
                        <li><i class="fa fa-check"><%= @game.unoxcero %></i></li>
                        <li><i class="fa fa-check"><%= @game.dosxcero %></i></li>
                        <li><i class="fa fa-check"><%= @game.dosxuno%></i></li>
                        <li><i class="fa fa-check"><%= @game.tresxcero%></i></li>
                        <li><i class="fa fa-check"><%= @game.tresxuno%></i></li>
                        <li><i class="fa fa-check"><%= @game.tresxdos%></i></li>
                        <li><i class="fa fa-check"><%= @game.cuatroxcero%></i></li>
                        <li><i class="fa fa-check"><%= @game.cuatroxuno%></i></li>
                        <li><i class="fa fa-check"><%= @game.cuatroxdos%></i></li>
                        <li><i class="fa fa-check"><%= @game.cuatroxtres%></i></li>
                        <li><i class="fa fa-check"><%= @game.cincoxcero%></i></li>
                        <li><i class="fa fa-check"><%= @game.ceroxcero%></i></li>
                        <li><i class="fa fa-check"><%= @game.unoxuno%></i></li>
                        <li><i class="fa fa-check"><%= @game.dosxdos%></i></li>
                        <li><i class="fa fa-check"><%= @game.tresxtres%></i></li>
                        <li><i class="fa fa-check"><%= @game.cuatroxcuatro%></i></li>
                        <li><i class="fa fa-check"><%= @game.ceroxuno%></i></li>
                        <li><i class="fa fa-check"><%= @game.ceroxdos%></i></li>
                        <li><i class="fa fa-check"><%= @game.unoxdos%></i></li>
                        <li><i class="fa fa-check"><%= @game.ceroxtres%></i></li>
                        <li><i class="fa fa-check"><%= @game.unoxtres%></i></li>
                        <li><i class="fa fa-check"><%= @game.dosxtres%></i></li>
                        <li><i class="fa fa-check"><%= @game.ceroxcuatro%></i></li>
                        <li><i class="fa fa-check"><%= @game.unoxcuatro%></i></li>
                        <li><i class="fa fa-check"><%= @game.dosxcuatro%></i></li>
                        <li><i class="fa fa-check"><%= @game.tresxcuatro%></i></li>
                        
                        
                        
                    </ul>
                </div>
            
            </div>
             <div class="col-sm-2 col-2 col-xs-12 no-padding">
             	 <div class="features-table-paid">
                	<ul>
                    	<h1>Ganancias</h1>
                        <li><i class="fa fa-check" id="sumadas">0</i></li>
                        <li><i class="fa fa-check" id="sumadas1">0</i></li>
                        <li><i class="fa fa-check" id="sumadas2">0</i></li>
                        <li><i class="fa fa-check" id="sumadas3">0</i></li>
                        <li><i class="fa fa-check" id="sumadas4">0</i></li>
                        <li><i class="fa fa-check" id="sumadas5">0</i></li>
                        <li><i class="fa fa-check" id="sumadas6">0</i></li>
                        <li><i class="fa fa-check" id="sumadas7">0</i></li>
                        <li><i class="fa fa-check" id="sumadas8">0</i></li>
                        <li><i class="fa fa-check" id="sumadas9">0</i></li>
                        <li><i class="fa fa-check" id="sumadas10">0</i></li>
                        <li><i class="fa fa-check" id="sumadas11">0</i></li>
                        <li><i class="fa fa-check" id="sumadas12">0</i></li>
                        <li><i class="fa fa-check" id="sumadas13">0</i></li>
                        <li><i class="fa fa-check" id="sumadas14">0</i></li>
                        <li><i class="fa fa-check" id="sumadas15">0</i></li>
                        <li><i class="fa fa-check" id="sumadas16">0</i></li>
                        <li><i class="fa fa-check" id="sumadas17">0</i></li>
                        <li><i class="fa fa-check" id="sumadas18">0</i></li>
                        <li><i class="fa fa-check" id="sumadas19">0</i></li>
                        <li><i class="fa fa-check" id="sumadas20">0</i></li>
                        <li><i class="fa fa-check" id="sumadas21">0</i></li>
                        <li><i class="fa fa-check" id="sumadas22">0</i></li>
                        <li><i class="fa fa-check" id="sumadas23">0</i></li>
                        <li><i class="fa fa-check" id="sumadas24">0</i></li>
                        <li><i class="fa fa-check" id="sumadas25">0</i></li>
                    
                        
                        
                    </ul>
                </div>
             </div>
        </div>
  


<%= link_to 'Editar', edit_game_path(@game) %>

<%= link_to "Procesar apuesta", new_game_bet_path(@game), :class => "btn btn-default btn-lg" %>