config/routes.rb
Rails.application.routes.draw do
  
  

  
  

  get 'new' =>'partidos#new'

  get 'partidos/create'

  get 'partidos/show'

  get 'static_pages/home'
  
  get 'futbols/opcion'
  
  get 'reviews/parse_comments'
  
resources :futbols do
  resources :reviews
end

resources :games do
  resources :bets
end

  

   root 'static_pages#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Locos por el futbol</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>    
    <!--<a class="navbar-brand" href="#">LOCOS POR EL FUTBOL</a>-->
    <%= link_to "LOCOS POR EL FUTBOL", futbols_path, :class => "navbar-brand"  %>
  </div>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "Lista partido por ganador", futbols_path %></li>
        <li><%= link_to "Lista partido por resultados", games_path %></a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Añadir partido por ganador", new_futbol_url %></li>
      <li><%= link_to "Añadir partido por resultado", new_game_url %></li>
    </ul>
  </div>
</nav>
<!--<header class="navbar  navbar-inverse">-->
<!--      <div class="container">-->
<!--        <%= link_to "LOCOS POR EL FUTBOL", '#', id: "logo" %>-->
<!--        <nav>-->
<!--          <ul class="nav navbar-nav navbar-right">-->
<!--            <li><%= link_to "Home",   root_path %></li>-->
<!--            <li><%= link_to "Añadir partido por ganador", new_futbol_url %></li>-->
<!--            <li><%= link_to "Añadir partido por resultado", new_game_url %></li>-->
<!--            <li><%= link_to "Log in", '#' %></li>-->
<!--          </ul>-->
<!--        </nav>-->
<!--      </div>-->
<!--    </header>-->
    
    <div class="container">
      <%= yield %>
    </div>
<!--<input type="hidden" id="refresh" value="no">-->
</body>
</html>